//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MotionPlan
{
    [Serializable]
    public class Gripper_cmdMsg : Message
    {
        public const string k_RosMessageName = "motion_plan/Gripper_cmd";
        public override string RosMessageName => k_RosMessageName;

        public bool close;

        public Gripper_cmdMsg()
        {
            this.close = false;
        }

        public Gripper_cmdMsg(bool close)
        {
            this.close = close;
        }

        public static Gripper_cmdMsg Deserialize(MessageDeserializer deserializer) => new Gripper_cmdMsg(deserializer);

        private Gripper_cmdMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.close);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.close);
        }

        public override string ToString()
        {
            return "Gripper_cmdMsg: " +
            "\nclose: " + close.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
